management:
  endpoints:
    web:
      exposure:
      include: '*'
  info:
    env:
      enabled: true

info:
  application:
    name: uber_app
    description: An app can make transportation easy and affordable
    author: kapi
    version: '@project.version@'
spring:
  profiles:
  active: prod